#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
#  This file is part of the `lipyd` python module
#
#  Copyright (c) 2015-2018 - EMBL
#
#  File author(s): Dénes Türei (turei.denes@gmail.com)
#
#  This code is not for public use.
#  Please do not redistribute.
#  For permission please contact me.
#
#  Website: http://www.ebi.ac.uk/~denes
#

from __future__ import print_function
from future.utils import iteritems
from past.builtins import xrange, range, reduce

import itertools

import lipyd.fragment as fragment
import lipyd.formula as formula
import lipyd.settings as settings


class FragmentDatabaseAggregator(object):
    
    def __init__(
            self,
            ionmode = 'pos',
            files = None,
            include = None,
            exclude = None,
            fa_default  = None,
            sph_default = None
        ):
        """
        Builds and serves a database of MS2 fragment ions according to
        certain criteria.
        
        Fragments data can be either read from built in or user provided
        files, or homolog series of alkyl chain containing fragments
        can be generated by classes provided in the `fragment` module.
        You can select which of these homolog series should be generated
        and by which parameters. By default fragments from the built in
        list are read to avoid this provide a value for `files` argument.
        This might be an empty list or a list of files with your custom
        fragments, or a single filename string.
        
        Args
        ----
        :param str ionmode:
            Ion mode, either `pos` or `neg`.
        :param str,list files:
            Fragment list filenames. List of filenames or a single
            filename. If `None` the built in fragment list file used.
        :param list include:
            List of homolog series classes. Names of class defined in
            the `fragment` module, optionally tuples of class names
            and dict of arguments.
        :param list exclude:
            List of class names not to be used to generate fragment
            series.
        :param dict fa_default:
            Default arguments for fatty acyl or fatty alkyl derived
            fragment series.
        :param dict sph_default:
            Default arguements for sphingoid long chain base derived
            fragment series.
        """
        
        self.mode  = ionmode
        self.files = files
        self.include = include
        self.exclude = exclude
        self.fa_default  = fa_default  or {}
        self.sph_default = sph_default or {}
    
    def build(self):
        """
        Builds the fragment list.
        
        Reads files and auto-generates programmatically calculated
        homolog series.
        """
        
        self.set_filenames()
        self.fragments = self.read_files()
    
    def set_filenames(self):
        """
        Sets the `files` attribute to be a list of filenames.
        If no `files` argument provided the built in default
        fragment list files will be used.
        """
        
        self.files = (
                [self.files]
            if hasattr(self.files, 'lower') else
                [self.get_default_file()]
            if self.files is None else
                self.files
        )
    
    def get_default_file(self):
        """
        Returns the file name of the default fragment lists.
        
        These are stored in the `pfragmentsfile` and `nfragmentsfile`
        settings for positive and negative ion modes, respectively.
        The fragment list files should have at least 4 columns:
            * m/z as float
            * formula -- either formula or m/z should be provided,
              mass calculation from formula has priority over the
              mass in first column
            * human readable name
            * type: e.g. `[M+H]+`; importantly, for neutral losses
              this value must start with `NL`
            * headgroups (lipid classes), e.g.`PC;SM`
        
        See the built in fragment lists for examples.
        """
        
        return settings.get('%sfragmentsfile' % (
            'p' if self.mode == 'pos' else 'n'
        ))
    
    def read_files(self):
        """
        Returns the list of fragments read from all files.
        """
        
        return (
            list(
                itertools.chain(
                    *(self.read_file(fname) for fname in self.files)
                )
            )
        )
    
    def read_file(self, fname = None):
        """
        Reads a list of MS2 fragments from a file.
        Returns list of fragments.
        
        If no filename provided the default fragment lists will be read.
        The fragment list files should have at least 4 columns:
            * m/z as float
            * formula -- either formula or m/z should be provided,
              mass calculation from formula has priority over the
              mass in first column
            * human readable name
            * type: e.g. `[M+H]+`; importantly, for neutral losses
              this value must start with `NL`
            * headgroups (lipid classes), e.g.`PC;SM`
        
        See the built in fragment lists for examples.
        """
        
        def process_line(l):
            
            l = l.split('\t')
            
            mass = (
                    formula.Formula(l[1]).mass
                if l[1] else
                    float(l[0])
                if l[0] else
                    None
            )
            
            return [mass, l[2], l[3], l[4]]
        
        fname = fname or self.get_default_file()
        
        with open(fname, 'r') as fp:
            
            return [
                ll for ll in
                    (
                        process_line(l) for l in
                        filter(bool, fp.read().split('\n'))
                    )
                if ll and ll[0]
            ]
